### ISSUE TITLE
Feature: <Stack />

### ISSUE THREAD

**Issue by vmarcosp** [rescriptbr/ancestor#2]
## Feature: `<Stack />`
N/A

## Draft
```rescript
open Ancestor

<Stack gap=[xxs(2)] align=[xxs(#center), md(#"flex-end")]>
....
</Stack>
```

## References
- [Braid's Stack](https://seek-oss.github.io/braid-design-system/components/Stack)
- [Chakra UI's Stack](https://chakra-ui.com/docs/components/stack)

**Comment by tom-sherman** [comment]
@vmarcosp Would love to use ancestor in my ReScript React app, but stack is a must for me. Do you need any help with getting this over the line?

**Comment by vmarcosp** [comment]
Hey @tom-sherman. Glad to see you're interested in Ancestor :)
Of course, I appreciate if you could help me with this feature. Actually, add new components like Stack is easy we have just to define an API (I mean, the props like direction, align, etc).
Do you any suggestions or references?
We could use this feature to discuss an API for this component.

**Comment by tom-sherman** [comment]
I've a built a few Stack components and every time I've pretty much copied the API from https://seek-oss.github.io/braid-design-system/components/Stack

Do you think it could be shipped initially with just the space/gap prop? Extra features like align, dividers, and direction could be added later

**Comment by vmarcosp** [comment]
Yeah, of course! 
I would do the same. Do you want to make a PR? 
I don't have a contributing guide yet, but should be easy to clone the repo and get everything running.
Also, there are some requirements to add a new component:
- 1. Every component should have its specific props + system props defined [here](https://ancestor.rescriptbrasil.org/docs/system-props) + dom props (might be painful, unfortunately 😞 )
. It's simple, just copy and paste from [`Box`](https://github.com/rescriptbr/ancestor/blob/main/lib/src/components/box/Ancestor_Box.res) or `Grid`.
- 2. Every component should use `Base` to inherit props like `tag`. You can use the `Box` component a guide too.

I have plans to create a contributing guide, explaining how to create new components and how to add all system props

**Comment by tom-sherman** [comment]
Cool, I'll give it a go.

Is the implementation ok to use flex gap?
