### ISSUE TITLE
Why use ppx-ts?

### ISSUE THREAD

**Issue by woeps** [rescriptbr/ancestor#94]
Hi,

I saw you are using [`@greenlabs/ppx-ts/ppx`](https://github.com/green-labs/ppx_ts) (`keyOf`) only at [core/Ancestor.res#5](https://github.com/rescriptbr/ancestor/blob/3e33537d00b4a615caf9a81dbc1b0e177bd2e8db/packages/core/src/Ancestor.res#L5).

I'm wondering if it would make sense to just hard-code this one type manually?

Personally - as a future ancestor user - I'd like to see as few ppx's involved as possible. - for the sake of simplicity and performance

**Comment by vmarcosp** [comment]
Hey!
That's a good question.
The usage of ppx-ts is temporally. For now, I'm using it to generate a few types and reducing boilerplate, but probably I'll provide a new customization API instead that doesn't need this kind of magic.
