### ISSUE TITLE
Building on top of bs-css vs rolling your own emotion wrapper

### ISSUE THREAD

**Issue by woeps** [rescriptbr/ancestor#95]
I saw you invested a lot of effort into writing your own emotion wrapper.

I'm curious if you considered building on top of [bs-css](https://github.com/giraud/bs-css/)? And if so, why you didn't?

**Comment by vmarcosp** [comment]
I love `bs-css` and I used a lot in many projects. I considered building Ancestor on top of it but I'm afraid that the project isn't focused on ReScript, since they want to support Reason too. 
I could change my css implementation to use the "atomic types" from bs-css but I'll keep the API that I created on top of the new optional record api. But, that's a good question, I can use the bs-css atomic types instead of creating mine from scratch (like I did) and create a new api on top of its types. What do you think as a future user?

**Comment by vmarcosp** [comment]
Hey @giraud, thanks for clarifying the future of bs-css. Having said that, @woeps I'll build the ancestor's css module on top of bs-css but keeping the same api using optional record fields.

@giraud Just a suggestion, don't you think that the name bs-css doesn't tell much about the project? Why not something like re-css or ml-css, or even rescript-css. `bs` stands for `buckelscript`, right? Please don’t take this as criticism 😄

**Comment by giraud** [comment]
I know, but I always favor backward compatibility and I want to avoid project renaming: it would have a big impact on existing projects and I don’t like that idea. Finally, bs is abstracted enough that it doesnt tie the lib to reasonml or rescript !

**Comment by vmarcosp** [comment]
It makes sense, thanks for answering 😄

**Comment by woeps** [comment]
Let me try to state the problem you were facing in my own words and please verify if I understood correct:

- by using a functor in [AncestorCss_Types.res:87](https://github.com/rescriptbr/ancestor/blob/1f54b860723ab907c679229ea4c644c274e3d737/packages/css/src/AncestorCss_Types.res#L87) you are making you CSS types aware of potentially user defined types
- any ancestor component functor calls this functor (again) on it's own to enable a dev to use these custom types directly

## Problem 1: CSS types parameterized
Since your CSS types are being made aware of custom types it's not a task of just "replacing some type here and there" because `bs-css` does not work like this.

To solve this, the order of evaluation would need to change:
- any user typed value would have to be converted to `bs-css` core types first
- afterwards all style values would get passed to some css-in-js implementation

*We would need to verify how much of the code ends up being called during app runtime and which parts could be bundled beforehand to optimize performance and bundlesize.*

## Problem 2: type identity
Another issue I believe I have found is, that you heavily rely on poly variants not being nomenal typed.
Have you tried using other types? I believe the usage of nomenal types (like normal variants) would bring up the issue, that each call to the CSS types functor would create a separate type on it's own. (An issue, since the functor is called multiple times.)

This could probably be solved (looking at this issue exclusively) by calling the css types functor just once and pass this to all component functors. And/Or have module types using `with` constraints to replace the types in the signature with the custom ones. By doing so it's possible, that all functors use the same nomenal type.

## Opportunity to make ancestor css-in-js lib agnostic
If `bs-css` could be used it might open up the possibility for Ancestor to be used with any css-in-js imementation compatible with `bs-css`.

I'd like to find some time to play around with a fork of your codebase and see if I can come up with some feasable suggestions.

**Comment by woeps** [comment]
Let me try to state the problem you were facing in my own words and please verify if I understood correct:

- by using a functor in [AncestorCss_Types.res:87](https://github.com/rescriptbr/ancestor/blob/1f54b860723ab907c679229ea4c644c274e3d737/packages/css/src/AncestorCss_Types.res#L87) you are making you CSS types aware of potentially user defined types
- any ancestor component functor calls this functor (again) on it's own to enable a dev to use these custom types directly

## Problem 1: CSS types parameterized
Since your CSS types are being made aware of custom types it's not a task of just "replacing some type here and there" because `bs-css` does not work like this.

To solve this, the order of evaluation would need to change:
- any user typed value would have to be converted to `bs-css` core types first
- afterwards all style values would get passed to some css-in-js implementation

*We would need to verify how much of the code ends up being called during app runtime and which parts could be bundled beforehand to optimize performance and bundlesize.*

## Problem 2: type identity
Another issue I believe I have found is, that you heavily rely on poly variants not being nomenal typed.
Have you tried using other types? I believe the usage of nomenal types (like normal variants) would bring up the issue, that each call to the CSS types functor would create a separate type on it's own. (An issue, since the functor is called multiple times.)

This could probably be solved (looking at this issue exclusively) by calling the css types functor just once and pass this to all component functors. And/Or have module types using `with` constraints to replace the types in the signature with the custom ones. By doing so it's possible, that all functors use the same nomenal type.

## Opportunity to make ancestor css-in-js lib agnostic
If `bs-css` could be used it might open up the possibility for Ancestor to be used with any css-in-js imementation compatible with `bs-css`.
**Edit:** I just realized this is [already possible by shadowing the default CSS function in the config module](https://ancestor.rescriptbrasil.org/docs/customization/#css-in-js). The `css` function shall take a string (css) and return a class name.  
This us just another abstraction, compared to the way `bs-css` works.

---

I'd like to find some time to play around with a fork of your codebase and see if I can come up with some feasable suggestions.
